Repository PuddyProject/Puddy_FrontEnd, pull requests merged in 2023-04, with the labels that each got.

#41 [FEAT] 로그인 페이지 기능 구현, 하단 앱바 코드 리팩토링
  src/App.tsx
  src/components/common/NavBar.tsx
  src/constants/navItem.ts
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyProfileEditor/index.tsx
  src/pages/PetProfileEditor/index.tsx
  src/routes/index.tsx
  src/styles/layout/footer/_footer-app-bar.scss
  src/styles/pages/_login.scss
  src/utils/axiosHelper.ts
Labels: Feat, Refactor

#42 [FEAT] Q&A 페이지 통신 및 데이터 바인딩
  src/components/common/QnaCard.tsx
  src/components/qnaDetail/Comment.tsx
  src/pages/QnA/index.tsx
  src/pages/QnaAnswer/index.tsx
  src/pages/QnaDetail/index.tsx
  src/pages/QnaNewPost/index.tsx
  src/routes/index.tsx
  src/styles/components/_qna-card.scss
  src/styles/pages/_qna-detail.scss
  src/styles/pages/_qna.scss
  src/types/commentTypes.ts
  src/types/qnaCardTypes.ts
  src/utils/axiosHelper.ts
  src/utils/index.ts
  src/utils/initialValues/qnaDetail.ts
Labels: Feat

#43 [FEAT] JWT 토큰 디코드 유틸, 커스텀 훅 추가 & 펫 프로필 에디터 서버 통신 코드 추가
  src/components/common/Checkbox.tsx
  src/components/common/InputBox.tsx
  src/components/common/RadioButton.tsx
  src/components/common/TextArea.tsx
  src/hooks/.gitkeep
  src/hooks/useAuth.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyProfileEditor/index.tsx
  src/pages/PetProfileEditor/index.tsx
  src/styles/pages/_pet-profile-editor.scss
  src/types/petProfileTypes.ts
  src/types/userTokenTypes.ts
  src/utils/checkExtensions.ts
  src/utils/decodeJWT.ts
Labels: Feat

#44 [FEAT] 메인페이지 데이터 바인딩 작업 및 메인페이지 버튼 클릭시 해당 페이지 이동
  package.json
  src/components/main/MainQnaCard.tsx
  src/components/main/QnaContainer.tsx
  src/pages/Main/index.tsx
  src/styles/components/_qna-card.scss
  src/types/qnaCardTypes.ts
Labels: Feat

#46 [FEAT] Q&A 디테일 페이지 리펙토링
  src/App.tsx
  src/components/common/FooterButton.tsx
  src/components/main/ExpertContainer.tsx
  src/components/main/QnaContainer.tsx
  src/components/qnaDetail/Comment.tsx
  src/pages/Main/index.tsx
  src/pages/QnA/index.tsx
  src/pages/QnaAnswer/index.tsx
  src/pages/QnaDetail/index.tsx
  src/pages/QnaNewPost/index.tsx
  src/styles/components/_footer-button.scss
  src/styles/pages/_home.scss
  src/styles/pages/_newpost.scss
  src/styles/pages/_qna-detail.scss
  src/styles/pages/_qna.scss
  src/types/commentTypes.ts
  src/utils/initialValues/qnaDetail.ts
  src/utils/initialValues/userInfo.ts
Labels: Feat, Refactor

#47 [FEAT, REFACTOR] context API 추가, axios Helper 함수 리팩토링, 일부 페이지 서버 통신 코드 추가
  src/App.tsx
  src/context/PetContext.tsx
  src/context/UserContext.tsx
  src/hooks/useAuth.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyProfileEditor/index.tsx
  src/pages/PetProfile/index.tsx
  src/pages/PetProfileEditor/index.tsx
  src/routes/index.tsx
  src/styles/pages/_my-profile-editor.scss
  src/types/petProfileTypes.ts
  src/utils/axiosHelper.ts
  src/utils/initialValues/myProfileEditor.ts
  src/utils/validate/checkNickname.ts
Labels: Feat, Refactor

#49 [FEAT, REFACTOR] 상단, 하단 앱바 스타일 수정 및 리팩토링, 내 프로필 수정, 내 펫 프로필 수정 기능 추가
  src/components/common/Checkbox.tsx
  src/components/common/CustomHeader.tsx
  src/components/common/Header.tsx
  src/components/common/NavBar.tsx
  src/components/common/RadioButton.tsx
  src/components/common/TextArea.tsx
  src/components/index.ts
  src/constants/navItem.ts
  src/context/PetContext.tsx
  src/context/UserContext.tsx
  src/hooks/useAuth.tsx
  src/pages/AuthExpert/index.tsx
  src/pages/MyActivityInfo/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyProfileEditor/index.tsx
  src/pages/PetProfile/index.tsx
  src/pages/PetProfileEditor/index.tsx
  src/pages/QnaAnswer/index.tsx
  src/pages/QnaDetail/index.tsx
  src/pages/QnaNewPost/index.tsx
  src/pages/Signup/index.tsx
  src/routes/index.tsx
  src/styles/components/_inputbox.scss
  src/styles/components/_write-button.scss
  src/styles/layout/footer/_footer-app-bar.scss
  src/styles/layout/header/_center-header.scss
  src/styles/layout/header/_header.scss
  src/styles/layout/header/_left-header.scss
  src/styles/layout/header/_right-header.scss
  src/styles/pages/_pet-profile.scss
  src/types/petProfileTypes.ts
  src/utils/axiosHelper.ts
Labels: Feat, Refactor

#53 [FEAT] 전문가 프로필 등록, 전문가 프로필 보기 페이지
  src/constants/myPageList.ts
  src/context/PetContext.tsx
  src/pages/AuthExpert/index.tsx
  src/pages/ExpertProfile/index.tsx
  src/pages/ExpertProfileEditor/index.tsx
  src/pages/MyPage/index.tsx
  src/styles/layout/header/_left-header.scss
  src/styles/layout/header/_right-header.scss
  src/styles/pages/_expert-profile.scss
  src/types/expertProfileTypes.ts
Labels: Feat

#52 [FEAT, REFACTOR] Q&A 게시글 수정 및 삭제 완료 및 커뮤니티 카드 작업
  src/assets/Community_no_img.svg
  src/components/common/CommunityCard.tsx
  src/components/common/InputBox.tsx
  src/components/index.ts
  src/components/main/QnaContainer.tsx
  src/components/qnaDetail/CommunityComment.tsx
  src/components/qnaDetail/QnaComment.tsx
  src/constants/cardList.ts
  src/pages/CardDetail/index.tsx
  src/pages/CardList/index.tsx
  src/pages/Community/index.tsx
  src/pages/Main/index.tsx
  src/pages/NewPost/index.tsx
  src/pages/QnA/index.tsx
  src/pages/QnaAnswer/index.tsx
  src/pages/QnaDetail/index.tsx
  src/pages/QnaNewPost/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/components/_community-card.scss
  src/styles/components/_community-comment.scss
  src/styles/components/_qna-comment.scss
  src/styles/components/index.scss
  src/styles/pages/_card-detail.scss
  src/styles/pages/_card-list.scss
  src/styles/pages/_home.scss
  src/styles/pages/_newpost.scss
  src/styles/pages/index.scss
  src/utils/axiosHelper.ts
  src/utils/index.ts
Labels: Feat, Refactor

#56 [FEAT, REFACTOR] 로딩 컴포넌트 적용 및 커스텀 훅스 추가, 코드 스플리팅, API endpoint, routes Path 상수 분리 후 전체 페이지 적용
  src/components/common/Loading.tsx
  src/components/common/RadioButton.tsx
  src/components/index.ts
  src/constants/apiEndpoint.ts
  src/constants/kakaoLogin.ts
  src/constants/routes.ts
  src/context/PetContext.tsx
  src/hooks/useLoading.tsx
  src/pages/AuthExpert/index.tsx
  src/pages/ExpertProfile/index.tsx
  src/pages/ExpertProfileEditor/index.tsx
  src/pages/Login/Kakao.tsx
  src/pages/Login/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/Account.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyProfileEditor/index.tsx
  src/pages/PetProfile/index.tsx
  src/pages/PetProfileEditor/index.tsx
  src/pages/QnaAnswer/index.tsx
  src/pages/QnaDetail/index.tsx
  src/pages/QnaNewPost/index.tsx
  src/pages/Signup/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/abstracts/_animations.scss
  src/styles/components/_loading.scss
  src/styles/components/index.scss
  src/styles/pages/_account.scss
  src/styles/pages/_mypage.scss
  src/styles/pages/index.scss
  src/utils/axiosHelper.ts
Labels: Feat, Refactor

#59 [FEAT,REFACTOR] 게시글 검색 페이지 및 전문가 페이지 및 API 적용 방식 수정 및 전체적인 리펙토링
  src/components/common/CommunityCard.tsx
  src/components/common/ExpertCard.tsx
  src/components/common/QnaCard.tsx
  src/components/index.ts
  src/components/main/ExpertContainer.tsx
  src/components/qnaDetail/QnaComment.tsx
  src/constants/NewPost.ts
  src/constants/cardDetail.ts
  src/constants/cardList.ts
  src/constants/cardSearch.ts
  src/constants/qnaNewPost.ts
  src/constants/routes.ts
  src/pages/CardDetail/index.tsx
  src/pages/CardList/index.tsx
  src/pages/CardSearch/index.tsx
  src/pages/CommentAnswer/index.tsx
  src/pages/ExpertCardList/index.tsx
  src/pages/NewPost/index.tsx
  src/pages/QnaDetail/index.tsx
  src/pages/QnaNewPost/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/components/_community-card.scss
  src/styles/components/_qna-card.scss
  src/styles/pages/_card-detail.scss
  src/styles/pages/_card-list.scss
  src/styles/pages/_card-search.scss
  src/styles/pages/_home.scss
  src/styles/pages/_newpost.scss
  src/styles/pages/index.scss
  src/types/commentTypes.ts
  src/utils/currentPage.ts
  src/utils/initialValues/qnaDetail.ts
Labels: Feat, Refactor

#61 [FEAT] 리프레시 토큰 AES 암호화, 버튼 모달, 404 페이지, 내 게시글/댓글, 로그아웃, 회원탈퇴 페이지
  package.json
  src/components/common/ButtonModal.tsx
  src/components/common/CustomHeader.tsx
  src/components/common/InputBox.tsx
  src/components/common/TextArea.tsx
  src/constants/apiEndpoint.ts
  src/constants/routes.ts
  src/context/PetContext.tsx
  src/context/UserContext.tsx
  src/hooks/useAuth.tsx
  src/layouts/index.tsx
  src/pages/ExpertProfile/index.tsx
  src/pages/ExpertProfileEditor/index.tsx
  src/pages/Login/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyActivityInfo/index.tsx
  src/pages/MyPage/Account.tsx
  src/pages/MyPage/Withdrawal.tsx
  src/pages/MyProfileEditor/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/PetProfileEditor/index.tsx
  src/pages/Signup/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/abstracts/_animations.scss
  src/styles/components/_button-modal.scss
  src/styles/components/_modal.scss
  src/styles/components/index.scss
  src/styles/pages/_card-list.scss
  src/styles/pages/_login.scss
  src/styles/pages/_my-activity-info.scss
  src/styles/pages/_not-found.scss
  src/styles/pages/_signup.scss
  src/styles/pages/_withdrawal.scss
  src/styles/pages/index.scss
  src/utils/axiosHelper.ts
  src/utils/convertImageToFile.ts
  src/utils/cryptoRefreshToken.ts
  tsconfig.json
Labels: Feat

#64 [FEAT,REFACTOR] 전문가 리스트 페이지 완성 및 커뮤니티 댓글 완성 및 게시글 상세 페이지 진입 시 처음에는 버튼 안보이도록 수정
  src/components/common/ExpertCard.tsx
  src/components/index.ts
  src/components/main/ExpertContainer.tsx
  src/components/main/MainCardContainer.tsx
  src/components/main/MainQnaCard.tsx
  src/components/main/QnaContainer.tsx
  src/components/qnaDetail/CommunityComment.tsx
  src/components/qnaDetail/QnaComment.tsx
  src/constants/apiEndpoint.ts
  src/constants/routes.ts
  src/pages/CardDetail/index.tsx
  src/pages/CardList/index.tsx
  src/pages/CommentAnswer/index.tsx
  src/pages/ExpertCardList/index.tsx
  src/pages/Main/index.tsx
  src/pages/NewPost/index.tsx
  src/routes/index.tsx
  src/styles/components/_community-card.scss
  src/styles/components/_community-comment.scss
  src/styles/components/_qna-card.scss
  src/styles/components/_qna-comment.scss
  src/styles/pages/_card-detail.scss
  src/styles/pages/_home.scss
  src/types/commentTypes.ts
  src/types/mainCardTyeps.ts
  src/types/qnaCardTypes.ts
  src/utils/convertImageToFile.ts
  src/utils/index.ts
  src/utils/trimBody.ts
Labels: Feat, Refactor

#66 [FEAT] 소셜 로그인, 전문가 프로필 수정하기, 비밀번호 변경, 아이디/비밀번호 찾기 페이지 추가
  src/components/common/ButtonModal.tsx
  src/components/common/Modal.tsx
  src/components/signup/InputField.tsx
  src/constants/apiEndpoint.ts
  src/constants/routes.ts
  src/constants/token.ts
  src/context/UserContext.tsx
  src/pages/AuthExpert/index.tsx
  src/pages/Bookmark/index.tsx
  src/pages/ExpertProfile/index.tsx
  src/pages/ExpertProfileEditor/index.tsx
  src/pages/FindAccount/Id.tsx
  src/pages/FindAccount/Password.tsx
  src/pages/FindAccount/index.tsx
  src/pages/Login/Kakao.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/Account.tsx
  src/pages/MyPage/ChangePassword.tsx
  src/pages/Notification/index.tsx
  src/pages/PetProfileEditor/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/components/_button-modal.scss
  src/styles/components/_modal.scss
  src/styles/pages/_changePassword.scss
  src/styles/pages/_find-account.scss
  src/styles/pages/_id.scss
  src/styles/pages/_password.scss
  src/styles/pages/index.scss
  src/types/expertProfileTypes.ts
  src/utils/checkExtensions.ts
Labels: Feat

#67 [FIX] ExpertProfileEditor의 location 값이 초기화되지 않는 현상 수정
  src/pages/ExpertProfileEditor/index.tsx
Labels: Bug

#71 [FEAT] PWA 서비스워커, 매니페스트 파일 추가, 빌드 관련 수정사항
  .babelrc
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/index.tsx
  src/pages/Login/index.tsx
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
  src/utils/axiosHelper.ts
Labels: Feat
